spring.application.name=backend-smart-campus

################### 데이터베이스 연결 설정 ###################
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe    
spring.datasource.username=userb                             
spring.datasource.password=userb                             
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

################### JPA 설정 ###################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

################### SQL 초기화 설정(insert) ###################
spring.sql.init.mode=never
spring.sql.init.encoding=utf-8
spring.sql.init.data-locations=\
classpath:sql/userinfo-insert.sql,\
classpath:sql/professor-insert.sql,\
classpath:sql/admin-insert.sql,\
classpath:sql/student-insert.sql,\
classpath:sql/subject-insert.sql,\
classpath:sql/term-insert.sql,\
classpath:sql/classroom-insert.sql,\
classpath:sql/restaurant-menu-review-insert.sql,\
classpath:sql/book_insert.sql,\
classpath:sql/study_room_insert.sql,\
classpath:sql/chat_insert.sql,\
classpath:sql/notice_insert.sql,\
classpath:sql/lecture-insert.sql,\
classpath:sql/schedule-insert.sql,\
classpath:sql/enrollment-insert.sql
