CREATE SEQUENCE MENU_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE REVIEW_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;



CREATE OR REPLACE TRIGGER MENU_ID_TRIGGER
BEFORE INSERT ON MENU
FOR EACH ROW
BEGIN
  SELECT MENU_SEQ.NEXTVAL INTO :NEW.MENU_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER REVIEW_ID_TRIGGER
BEFORE INSERT ON review
FOR EACH ROW
BEGIN
  SELECT REVIEW_SEQ.NEXTVAL INTO :NEW.review_id FROM DUAL;
END;
/
